name: CI

on:
  push:
    branches: ["CI"] 

jobs:
  build:
    name: build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        # please submit PRs for any operating system YOU might want to use!
        # see: https://docs.github.com/en/actions/reference/runners/github-hosted-runners
        os: [macos-15, macos-26,  macos-26-intel, macos-15-intel, windows-2025, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Install UV
        uses: astral-sh/setup-uv@v6

      - name: Setup Python
        run: uv python install

      - name: Install uv project 
        run: uv sync --locked --all-extras --dev

      - name: Build Zig Binaries
        run: uv run python -m ziglang build #TODO: maybe test the zig library later?
      
      - name: Build Binary Folder 
        run: mkdir -p src/neurovolume/_native
        shell: bash
        
      - name: Build Python Library
        run: uv build

      - name: Test Python Library
        run: uv run pytest -s tests
